#!/usr/bin/env node
/**
 * Generate ecrecover test vectors for the Motoko secp256k1 package.
 *
 * Usage: node generate-vectors.mjs
 *
 * Requires: npm install ethers
 *
 * Outputs test vectors in a format that can be copy-pasted into Motoko test files.
 */

import { ethers } from "ethers";

function toMotokoBlob(hex) {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  const bytes = [];
  for (let i = 0; i < clean.length; i += 2) {
    bytes.push(`0x${clean.slice(i, i + 2)}`);
  }
  // Format as 8 bytes per line for readability
  const lines = [];
  for (let i = 0; i < bytes.length; i += 8) {
    lines.push("      " + bytes.slice(i, i + 8).join(", ") + ",");
  }
  return `Blob.fromArray([\n${lines.join("\n")}\n    ])`;
}

async function main() {
  console.log("// ─── secp256k1 ecrecover test vectors ───────────────────────────");
  console.log("// Generated by: node generate-vectors.mjs");
  console.log(`// Date: ${new Date().toISOString()}`);
  console.log("");

  // Test vector 1: Private key = 1 (simplest case)
  // Address should be 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf
  const wallet1 = new ethers.Wallet(
    "0x0000000000000000000000000000000000000000000000000000000000000001"
  );
  console.log(`// Vector 1: Private key = 1`);
  console.log(`// Address: ${wallet1.address}`);
  const msg1 = "test message for Haven AOL";
  const sig1 = await wallet1.signMessage(msg1);
  const hash1 = ethers.hashMessage(msg1);
  const { r: r1, s: s1, v: v1 } = ethers.Signature.from(sig1);
  console.log(`// Message: "${msg1}"`);
  console.log(`// Hash (prefixed): ${hash1}`);
  console.log(`// r: ${r1}`);
  console.log(`// s: ${s1}`);
  console.log(`// v: ${v1}`);
  console.log(`// Expected address: ${wallet1.address.toLowerCase()}`);
  console.log("");
  console.log("// Motoko format:");
  console.log(`let hash1 = ${toMotokoBlob(hash1)};`);
  console.log(`let r1 = ${toMotokoBlob(r1)};`);
  console.log(`let s1 = ${toMotokoBlob(s1)};`);
  console.log(`let v1 : Nat8 = ${v1};`);
  console.log(
    `let expected1 = ${toMotokoBlob(wallet1.address.toLowerCase())};`
  );
  console.log("");

  // Test vector 2: Hardhat Account #0
  const wallet2 = new ethers.Wallet(
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  );
  console.log(`// Vector 2: Hardhat Account #0`);
  console.log(`// Address: ${wallet2.address}`);
  const msg2 = "Haven AOL GateRequest";
  const sig2 = await wallet2.signMessage(msg2);
  const hash2 = ethers.hashMessage(msg2);
  const { r: r2, s: s2, v: v2 } = ethers.Signature.from(sig2);
  console.log(`// Message: "${msg2}"`);
  console.log(`// Hash (prefixed): ${hash2}`);
  console.log(`// r: ${r2}`);
  console.log(`// s: ${s2}`);
  console.log(`// v: ${v2}`);
  console.log(`// Expected address: ${wallet2.address.toLowerCase()}`);
  console.log("");
  console.log("// Motoko format:");
  console.log(`let hash2 = ${toMotokoBlob(hash2)};`);
  console.log(`let r2 = ${toMotokoBlob(r2)};`);
  console.log(`let s2 = ${toMotokoBlob(s2)};`);
  console.log(`let v2 : Nat8 = ${v2};`);
  console.log(
    `let expected2 = ${toMotokoBlob(wallet2.address.toLowerCase())};`
  );
  console.log("");

  // Test vector 3: Random wallet with EIP-712 typed data
  const wallet3 = new ethers.Wallet(
    "0x4c0883a69102937d6231471b5dbb6204fe512961708279f6a06e2e7e46e7b3e0"
  );
  console.log(`// Vector 3: EIP-712 typed data signing`);
  console.log(`// Address: ${wallet3.address}`);
  const domain = {
    name: "HavenAOL",
    chainId: 1,
    verifyingContract: "0x0000000000000000000000000000000000000001",
  };
  const types = {
    GateRequest: [
      { name: "evmAddress", type: "address" },
      { name: "transportPublicKey", type: "bytes32" },
      { name: "nonce", type: "uint256" },
    ],
  };
  const value = {
    evmAddress: wallet3.address,
    transportPublicKey: ethers.keccak256("0xDEADBEEF"),
    nonce: 42n,
  };
  const sig3 = await wallet3.signTypedData(domain, types, value);
  const hash3 = ethers.TypedDataEncoder.hash(domain, types, value);
  const { r: r3, s: s3, v: v3 } = ethers.Signature.from(sig3);
  console.log(`// EIP-712 digest: ${hash3}`);
  console.log(`// r: ${r3}`);
  console.log(`// s: ${s3}`);
  console.log(`// v: ${v3}`);
  console.log(`// Expected address: ${wallet3.address.toLowerCase()}`);
  console.log("");
  console.log("// Motoko format:");
  console.log(`let hash3 = ${toMotokoBlob(hash3)};`);
  console.log(`let r3 = ${toMotokoBlob(r3)};`);
  console.log(`let s3 = ${toMotokoBlob(s3)};`);
  console.log(`let v3 : Nat8 = ${v3};`);
  console.log(
    `let expected3 = ${toMotokoBlob(wallet3.address.toLowerCase())};`
  );
  console.log("");

  console.log("// ─── End of test vectors ──────────────────────────────────────────");
}

main().catch(console.error);
